server:
  port: 8104
spring:  datasource:    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pandemia
    username: postgres
    password: postgres
  jpa:    database: postgresql
    hibernate:      ddl-auto: update
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect